### ISSUE TITLE
Backslash is considered "invalid" token type

### ISSUE THREAD

**Issue by WebFreak001** [s-ludwig/sdlite#8]
current workaround:

https://github.com/Pure-D/sdlfmt/blob/eaea6ff29cc7f88bbb5ac429bb55936505c3264a/source/sdlfmt.d#L196

sample SDL:

```sdl
// Nodes can be separated into multiple lines
title \
	"Some title"
	
```

**Comment by WebFreak001** [comment]
Wait no this is broken, it's considered part of whitespace now (which I don't think is very good)

Can you instead just change it so `\` is a new backslash token type instead of invalid token type? Otherwise this currently breaks my [sdlfmt](https://github.com/Pure-D/sdlfmt/) project I think.

**Comment by s-ludwig** [comment]
Hmm, my reasoning for making it part of white space was that it would otherwise complicate the current parser, as well as a possible future StAX style parser. I'd also assume that for most formatting tasks, this should just work as expected - both, outputting as-is, as well as replacing the white space string with an arbitrary differing white space string, will work fine.

**Comment by WebFreak001** [comment]
comments are already tokens that are included, I think the backslashes have a similar complexity. For filtering one could for example skip over all `backslash comment{0,} eol`

So I think backslashes should rather be backslash tokens like this and the filtering code would just skip over them for the parser, but still expose them for the lexer.
